server:
  port: 8010

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5 # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10 # 发呆时间，即服务续约到期时间（缺省为90s）
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka

spring:
  application:
    name: EurekaClient

management:
  server:
    port: 8011
  endpoints:
    web:
      exposure:
        include: "*"
        # 暴露Actuator的所有端点(默认只暴露health和info；访问路径：IP:Port/actuator/health等)
  endpoint:
    health:
      show-details: always
