spring:
  profiles:
    active: dev
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
        # 暴露Actuator的所有端点(默认只暴露health和info；访问路径：IP:Port/actuator/health等)
  endpoint:
    health:
      show-details: always
