spring:
  profiles:
    active: dev
#management:
#  endpoint:
#    shutdown:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#        # 暴露Actuator的所有端点(SpringBoot 2.0写法)
#  server:
#    port: 5555
