server:
  port: 8300

spring:
  application:
    name: zipkin-server

zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      hosts: http://localhost:9200
      cluster: elasticsearch
      index: zipkin
      index-shards: 1
      index-replicas: 1
  collector:
    # Zipkin Server集成Kafka相关配置
    kafka:
      bootstrap-servers: localhost:9092
      zookeeper: localhost:2181
      topic: zipkin

eureka:
  instance:
    hostname: localhost # 不指定的话则取当前主机名
    lease-renewal-interval-in-seconds: 5 # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10 # 发呆时间，即服务续约到期时间（缺省为90s）
  client:
    region: region233
    service-url:
      #      zone1: http://192.168.0.123:8000/eureka
      #      zone1: http://server0:8000/eureka,http://server1:8001/eureka
      #      zone2: http://server2:8002/eureka,http://server3:8003/eureka
      zone1: http://localhost:8000/eureka
    availability-zones:
      region233: zone1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    web:
      server:
        auto-time-requests: false # 解决Zipkin界面无法访问问题
